DROP TABLE `activity_logs`;--> statement-breakpoint
DROP TABLE `ai_chat_history`;--> statement-breakpoint
DROP TABLE `approval_comments`;--> statement-breakpoint
DROP TABLE `approval_requests`;--> statement-breakpoint
DROP TABLE `businesses`;--> statement-breakpoint
DROP TABLE `campaign_activity_log`;--> statement-breakpoint
DROP TABLE `campaign_analytics`;--> statement-breakpoint
DROP TABLE `campaign_deliverables`;--> statement-breakpoint
DROP TABLE `campaign_milestones`;--> statement-breakpoint
DROP TABLE `campaign_team_members`;--> statement-breakpoint
DROP TABLE `campaign_templates`;--> statement-breakpoint
DROP TABLE `campaign_variants`;--> statement-breakpoint
DROP TABLE `campaigns`;--> statement-breakpoint
DROP TABLE `content_versions`;--> statement-breakpoint
DROP TABLE `credit_alert_history`;--> statement-breakpoint
DROP TABLE `credit_alert_thresholds`;--> statement-breakpoint
DROP TABLE `credit_usage`;--> statement-breakpoint
DROP TABLE `distributions`;--> statement-breakpoint
DROP TABLE `email_templates`;--> statement-breakpoint
DROP TABLE `error_logs`;--> statement-breakpoint
DROP TABLE `image_credits`;--> statement-breakpoint
DROP TABLE `journalist_beat_relations`;--> statement-breakpoint
DROP TABLE `journalist_beats`;--> statement-breakpoint
DROP TABLE `journalist_outreach`;--> statement-breakpoint
DROP TABLE `journalist_tag_relations`;--> statement-breakpoint
DROP TABLE `journalist_tags`;--> statement-breakpoint
DROP TABLE `journalists`;--> statement-breakpoint
DROP TABLE `media_list_contacts`;--> statement-breakpoint
DROP TABLE `media_lists`;--> statement-breakpoint
DROP TABLE `media_outlets`;--> statement-breakpoint
DROP TABLE `notification_preferences`;--> statement-breakpoint
DROP TABLE `partner_referrals`;--> statement-breakpoint
DROP TABLE `partners`;--> statement-breakpoint
DROP TABLE `payments`;--> statement-breakpoint
DROP TABLE `preset_prompts`;--> statement-breakpoint
DROP TABLE `press_release_distributions`;--> statement-breakpoint
DROP TABLE `press_release_templates`;--> statement-breakpoint
DROP TABLE `press_releases`;--> statement-breakpoint
DROP TABLE `saved_filters`;--> statement-breakpoint
DROP TABLE `scheduled_press_releases`;--> statement-breakpoint
DROP TABLE `social_accounts`;--> statement-breakpoint
DROP TABLE `social_media_accounts`;--> statement-breakpoint
DROP TABLE `social_media_posts`;--> statement-breakpoint
DROP TABLE `sports_teams`;--> statement-breakpoint
DROP TABLE `subscriptions`;--> statement-breakpoint
DROP TABLE `team_invitations`;--> statement-breakpoint
DROP TABLE `team_members`;--> statement-breakpoint
DROP TABLE `usage_tracking`;--> statement-breakpoint
DROP TABLE `webhook_configs`;--> statement-breakpoint
DROP TABLE `webhook_delivery_logs`;--> statement-breakpoint
DROP TABLE `website_research`;--> statement-breakpoint
DROP TABLE `word_count_credits`;