import { useState, useEffect } from "react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Loader2, CheckCircle2, Clock, AlertCircle, Circle, XCircle } from "lucide-react";
import { toast } from "sonner";


export default function MediaListCategories() {
  const [selectedType, setSelectedType] = useState<"genre" | "geography" | "industry">("genre");

  // Fetch categories (all types, filter client-side)
  const { data: allCategories, isLoading: categoriesLoading, refetch } = trpc.mediaList.getCategories.useQuery(
    {},
    {
      refetchInterval: 30000, // Poll every 30s
    }
  );

  const categories = allCategories?.filter((cat) => cat.type === selectedType);

  // Fetch credit balance
  const { data: creditBalance } = trpc.mediaList.getCredits.useQuery();

  // Fetch generation requests
  const { data: requests, refetch: refetchRequests } = trpc.mediaList.getGenerationRequests.useQuery();

  // Check category status mutation
  const checkStatus = trpc.mediaList.checkCategoryStatus.useMutation({
    onSuccess: (data) => {
      if (data.needsGeneration) {
        if (data.requestId) {
          toast.info("This list is already being generated by another user! You'll receive an email when it's ready.");
        } else {
          toast.success("Generation started! We're building this media list for you. You'll receive an email when it's ready.");
        }
        refetchRequests();
        refetch();
      } else {
        toast.success("This media list is ready to use!");
      }
    },
    onError: (error) => {
      toast.error(error.message);
    },
  });

  const getRequestStatus = (categoryId: number) => {
    return requests?.find((r) => r.categoryId === categoryId);
  };

  const handleCategoryClick = (categoryId: number, isPopulated: boolean) => {
    if (isPopulated) {
      // Navigate to contacts view
      window.location.href = `/media-lists/${categoryId}`;
    } else {
      // Check status and queue generation
      checkStatus.mutate({ categoryId });
    }
  };

  return (
    <div className="container mx-auto py-8">
      {/* Header */}
      <div className="mb-8">
        <div className="flex justify-between items-start mb-4">
          <div>
            <h1 className="text-4xl font-bold mb-2">Media List Categories</h1>
            <p className="text-muted-foreground text-lg">
              Browse and select media lists by genre, geography, or industry. Lists are automatically generated when you select them.
            </p>
          </div>
          <div className="text-right">
            <p className="text-sm text-muted-foreground mb-1">Credits</p>
            <p className="text-3xl font-bold">{creditBalance ?? 0}</p>
            <Link href="/credits">
              <a className="text-sm text-primary hover:underline">Buy More Credits</a>
            </Link>
          </div>
        </div>

        {/* Privacy Notice */}
        <Card className="bg-blue-50 border-blue-200">
          <CardContent className="pt-6">
            <p className="text-sm text-blue-900">
              🔒 <strong>Privacy Notice:</strong> Individual journalist contact details are proprietary information and are not displayed. 
              When you distribute a press release, our system sends personalized emails to journalists at the selected publications on your behalf.
            </p>
          </CardContent>
        </Card>
      </div>

      <Tabs value={selectedType} onValueChange={(v) => setSelectedType(v as typeof selectedType)}>
        <TabsList className="mb-6">
          <TabsTrigger value="genre">By Genre</TabsTrigger>
          <TabsTrigger value="geography">By Geography</TabsTrigger>
          <TabsTrigger value="industry">By Industry</TabsTrigger>
        </TabsList>

        <TabsContent value={selectedType}>
          {categoriesLoading ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {categories?.map((category) => {
                const request = getRequestStatus(category.id);
                const isGenerating = request?.status === "pending" || request?.status === "processing";
                const isFailed = request?.status === "failed";

                return (
                  <Card
                    key={category.id}
                    className="cursor-pointer hover:shadow-lg transition-shadow"
                    onClick={() => handleCategoryClick(category.id, category.isPopulated)}
                  >
                    <CardHeader>
                      <div className="flex items-start justify-between">
                        <CardTitle className="text-lg">{category.name}</CardTitle>
                        {category.isPopulated ? (
                          <Badge className="bg-green-500 text-white">
                            <CheckCircle2 className="h-3 w-3 mr-1" />
                            Ready
                          </Badge>
                        ) : isGenerating ? (
                          <Badge className="bg-yellow-500 text-white">
                            <Clock className="h-3 w-3 mr-1" />
                            Being Generated
                          </Badge>
                        ) : isFailed ? (
                          <Badge className="bg-red-500 text-white">
                            <XCircle className="h-3 w-3 mr-1" />
                            Failed
                          </Badge>
                        ) : (
                          <Badge variant="outline" className="text-muted-foreground">
                            <Circle className="h-3 w-3 mr-1" />
                            Not Generated
                          </Badge>
                        )}
                      </div>
                      {category.description && (
                        <CardDescription className="mt-2">{category.description}</CardDescription>
                      )}
                    </CardHeader>
                    <CardContent>
                      {category.isPopulated ? (
                        <>
                          {request?.contactsGenerated && (
                            <>
                              <p className="text-sm font-medium">
                                {request.contactsGenerated} contacts
                              </p>
                              <p className="text-sm text-muted-foreground">
                                Publications found
                              </p>
                            </>
                          )}
                          <p className="text-sm text-muted-foreground mt-2">
                            Click to view publications
                          </p>
                        </>
                      ) : isGenerating ? (
                        <>
                          <div className="flex items-center gap-2">
                            <Loader2 className="h-4 w-4 animate-spin" />
                            <p className="text-sm text-muted-foreground">
                              AI is researching journalists...
                            </p>
                          </div>
                          <p className="text-xs text-muted-foreground mt-1">
                            Usually takes 5-10 minutes
                          </p>
                        </>
                      ) : isFailed ? (
                        <p className="text-sm text-destructive">
                          Generation failed. Click to retry.
                        </p>
                      ) : (
                        <p className="text-sm text-muted-foreground">
                          Click to generate this list
                        </p>
                      )}
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          )}
        </TabsContent>
      </Tabs>

      {/* Generation Queue Status */}
      {requests && requests.length > 0 && (
        <div className="mt-8">
          <h2 className="text-xl font-semibold mb-4">Your Generation Requests</h2>
          <div className="space-y-2">
            {requests
              .filter((r) => r.status === "pending" || r.status === "processing")
              .map((request) => (
                <Card key={request.id}>
                  <CardContent className="flex items-center justify-between py-4">
                    <div>
                      <p className="font-medium">{request.categoryName}</p>
                      <p className="text-sm text-muted-foreground">
                        Requested {new Date(request.requestedAt).toLocaleString()}
                      </p>
                    </div>
                    <Badge variant="secondary">
                      <Loader2 className="h-3 w-3 mr-1 animate-spin" />
                      {request.status}
                    </Badge>
                  </CardContent>
                </Card>
              ))}
          </div>
        </div>
      )}
    </div>
  );
}
